### ISSUE TITLE
Players won't leave the bed, when enough players are in bed and there is a thunderstorm

### ISSUE THREAD

**Issue by BrainStone** [Icohedron/SleepVote#3]
I went to bed during a thunderstorm, to skip it, however neither did the weather get cleared, nor did I leave the bed when the plugin said "good morning".

**Comment by Icohedron** [comment]
Ah, I forgot about that scenario!
I'll fix it ASAP.

**Comment by Icohedron** [comment]
Should be fixed now (v0.4.1).
