### ISSUE TITLE
Number of people not consistent

### ISSUE THREAD

**Issue by LJack2k** [Icohedron/SleepVote#4]
I'm using a "required_percent_sleeping" = 0.25 but the it's not consistent in the number of people that are required to sleep. For example when 4 people are online, one person should be enough to pass the vote. This works sometimes and sometimes it requires 2 people to sleep.

**Comment by Icohedron** [comment]
Probably because I used Math.ceil to calculate the number of required players and floating point precision. So when 4*0.25 was calculated to be 1.000001, it rounded up to 2.

No idea what I was thinking when making that! I'll change it ASAP.

**Comment by Icohedron** [comment]
Should be fixed in v0.4.2.
