### ISSUE TITLE
Is sleepvote no longer supported on Bukkit/spigot?

### ISSUE THREAD

**Issue by PsychoNavigator** [Icohedron/SleepVote#7]

**Comment by Icohedron** [comment]
SleepVote is a Sponge plugin. It was never made to support Bukkit/Spigot. If you are looking for a similar plugin for Bukkit/Spigot, [Better Beds](https://www.spigotmc.org/resources/better-beds.1824/) may suit your needs.

**Comment by PsychoNavigator** [comment]
https://dev.bukkit.org/projects/sleepvote

So, not yours then?

**Comment by Icohedron** [comment]
No, it's not mine.
![alt text](http://i.imgur.com/DRdg9Do.png)

**Comment by PsychoNavigator** [comment]
People come and go on dev teams. 

Cheers anyway!
