### ISSUE TITLE
Required Players not calculating correctly according to percentage

### ISSUE THREAD

**Issue by sobrinth** [Icohedron/SleepVote#8]
When configured to use percentage of online players the plugin wrongfully calculated the needed number.

This was the case for me, when is set "required_percent_sleeping" = 0.6 which led on my server to the situation when 3 players where online in which only one player was required to sleep in order to set the time to day.
I fixed this locally for my server by changing the code in SleepVoteManager:199 from:
`int requiredFromPercent = (int) (players.size() * requiredPercentSleeping);`
to:
`int requiredFromPercent = (int) (Math.ceil(players.size() * requiredPercentSleeping));`

**Comment by Icohedron** [comment]
"It's not a bug, it's a feature!"
The plugin will round down the number of players required to sleep. `(int) (3 * 0.6) = (int) 1.8 = 1`
This was done to address issue #4 and to make the plugin more "lenient" on the number of players required.

When I get to working on this plugin I'll make the configuration even more customizable and replace the floating point values with doubles:
- There will be an option to choose min() or max() between "required_number_sleeping" and "required_percent_sleeping"
- There will also be an option to use ceil() or floor() when calculating `requiredFromPercent`.
- Double precision will be used to prevent issue #4
